# Simulation configuration for cw_bw

# General simulation settings
nEvents: 3000

# 10-20%, 20-30%, 30-40%, 40-50%, 50-60%
# Negative Binomial distribution parameters
mu5TeV:   [1888, 1257, 2000, 508, 292]
NBDSigma: [300, 180, 124, 87, 63]
NBDLow:   [1300, 900, 3500, 400, 300]
NBDHigh:  [5000, 3000, 5000, 1200, 1000]
KinCutRatio: [0.43209614, 0.431945, 0.428783, 0.4336, 0.428906]

# Kinetic freeze-out temperature per centrality bin
Tkin:   [0.094, 0.097, 0.107, 0.108, 0.115]
TkinSigma: [0.003,0.003,0.000,0.003,0.003]
# Blast-Wave flow parameters
betaT:  [0.655, 0.643, 0.855, 0.595, 0.557]
betaTSigma: [0.002,0.002,0.000,0.002,0.002]
n:      [0.739, 0.771, 1.31, 0.908, 1.052]
rho2_p: [0.0649528, 0.0927472, 0.0942, 0.119152, 0.129067]
rho2_pion: [0.0701475, 0.088043, 0.0942, 0.0969142, 0.108739]
rho2_kaon: [0.0701475, 0.088043, 0.0942, 0.0969142, 0.108739]
Rx:     [8.37998, 7.78801, 8.29055, 7.26074, 7.11325]
# fracLBC: [0.0775, 0.0787, 0.0795, 0.0719, 0.0887] # from Δδ pol3 fit
#fracLBC [0.0491, 0.0534, 0.0581, 0.0523, 0.0851] # from Δγ

# Particle ratio
ratioProtonPion: 0.05
ratioKaonPion: 0.14
